
[server]
#address = "192.168.0.9:4000"
address = "127.0.0.1:4000"
file_server_path = "static" # Change name to front build path

[server.endpoints]
pod_data = "/podDataStructure"
order_data = "/orderStructures"
websocket = "/backend"
file_server = "/"

[vehicle]
tcp_client_tag = "TCP_CLIENT"
tcp_server_tag = "TCP_SERVER"
udp_tag = "UDP"
# network = { mtu = 1500, sniffer_interface = "\\Device\\NPF_{015224CF-DC7F-4F81-AA58-947027697645}" }
network = { mtu = 1500, interface = "lo" }
[vehicle.messages]
fault_id_key = "fault"
warning_id_key = "warning"
blcu_ack_id = "blcu_ack"

[excel.download]
id = "1BEwASubu0el9oQA6PSwVKaNU-Q6gbJ40JR6kgqguKYE"
credentials = "./secret.json"
name = "ade.xlsx"
path = "."

[excel.parse]
global_sheet_prefix = "GLOBAL "
board_sheet_prefix = "BOARD "
table_prefix = "[TABLE] "
[excel.parse.global]
address_table = "addresses"
backend_entry_key = "Backend"
units_table = "units"
ports_table = "ports"
board_ids_table = "board_ids"
message_ids_table = "message_ids"

[logger]
topics = { enable = "logger/enable", state = "logger/state" }

[logger.data_logger]
base_path = "log/data"

[logger.message_logger]
base_path = "log/message"
file_name = "messages.csv"

[orders]
send_topic = "order/send"

[messages]
update_topic = "message/update"

[data_transfer]
fps = 30
topics = { update = "podData/update" }

[connections]
update_topic = "connection/update"

[blcu.packets]
upload = { id = 700, field = "board" }
download = { id = 701, field = "board" }
ack = { name = "tftp_ack" }

[blcu.topics]
upload = "blcu/upload"
download = "blcu/download"
